trigger:
- main

pool:
  vmImage: 'windows-latest'
  name: Default

steps:
- checkout: self

- task: Docker@2
  inputs:
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'
    imageName: 'my-custom-image'
  displayName: 'Build Docker Image'


- script: |
    docker ps -a --filter "name=mycontainer" -q | ForEach-Object { docker rm -f $_ }
    docker run --name mycontainer mydockerimage:latest C:\android-sdk\cmdline-tools\latest\bin\sdkmanager.bat --licenses
  displayName: 'Run Container and Accept Licenses'
  
- powershell: |
    echo "Stopping Docker container..."
    docker stop my-container
    docker rm my-container
  displayName: 'Stop and Remove Docker Container'
  condition: always()  # Ensure cleanup runs even if previous steps fail
