trigger:
- main

pool:
  vmImage: 'windows-latest'
  name: Default

steps:
- checkout: self

- script: |
    echo "Building Docker image..."
    docker build -t android-sdk-image .
  displayName: 'Build Docker Image'

- script: |
    echo "Removing existing container if it exists..."
    docker rm -f android-sdk-container || true
  displayName: 'Remove Existing Container'

- script: |
    echo "Running Docker container..."
    docker run --name android-sdk-container -d android-sdk-image powershell -Command "Start-Sleep -Seconds 3600"
  displayName: 'Run Docker Container'

- script: |
    echo "Accepting Android SDK licenses..."
    docker exec android-sdk-container cmd /c "
    echo Attempting to accept Android SDK licenses...
    set SDKMANAGER=C:\Users\v-adamarla\AppData\Local\Android\Sdk\cmdline-tools\latest\bin\sdkmanager.bat
    if exist %SDKMANAGER% (
        echo Found sdkmanager at: %SDKMANAGER%
        echo y | %SDKMANAGER% --licenses
    ) else (
        echo sdkmanager not found at expected location. Please check your Android SDK installation.
        exit /b 1
    )
    "
  displayName: 'Accept Android SDK Licenses'

- script: |
    echo "Installing Android SDK components..."
    docker exec android-sdk-container cmd /c "
    set SDKMANAGER=C:\Users\v-adamarla\AppData\Local\Android\Sdk\cmdline-tools\latest\bin\sdkmanager.bat
    if exist %SDKMANAGER% (
        %SDKMANAGER% "platform-tools" "platforms;android-28" "build-tools;28.0.3"
    ) else (
        echo sdkmanager not found at expected location. Please check your Android SDK installation.
        exit /b 1
    )
    "
  displayName: 'Install Android SDK Components'

- script: |
    echo "Verifying ADB installation..."
    docker exec android-sdk-container cmd /c "
    set ADB=C:\Users\v-adamarla\AppData\Local\Android\Sdk\platform-tools\adb.exe
    if exist %ADB% (
        %ADB% version
    ) else (
        echo ADB not found at expected location. Please check your Android SDK installation.
        exit /b 1
    )
    "
  displayName: 'Verify ADB Installation'

- script: |
    echo "Running appium-doctor..."
    docker exec android-sdk-container appium-doctor
  displayName: 'Run Appium Doctor'

- script: |
    echo "Cleaning up..."
    docker stop android-sdk-container
    docker rm android-sdk-container
  displayName: 'Clean Up'
