trigger:
- main  # Adjust to your branch name if necessary

pool:
   vmImage: 'windows-latest' 
   name: Azure Pipelines  # Change to 'windows-latest' if using a Windows agent

steps:
- checkout: self


- script: |
    echo Accepting SDK licenses and installing required packages...
    docker exec myAppContainer powershell -Command "yes | C:\android-sdk\cmdline-tools\latest\bin\sdkmanager.bat --licenses"
    docker exec myAppContainer powershell -Command "C:\android-sdk\cmdline-tools\latest\bin\sdkmanager.bat 'platform-tools' 'platforms;android-28' 'build-tools;28.0.3'"
    docker exec myAppContainer powershell -Command "adb version"
    docker exec myAppContainer powershell -Command "appium-doctor"
  displayName: 'Run setup commands in Docker container'
