trigger:
- main

pool:
  vmImage: 'windows-latest'
  name: Default

steps:
- checkout: self

- script: |
    echo "Building Docker image..."
    docker build -t my-custom-image:latest .
  displayName: 'Build Docker Image'

- script: |
    echo "Removing existing container if it exists..."
    docker rm -f my-container || true
  displayName: 'Remove Existing Container'

- script: |
    echo "Running Docker container with mounted volume..."
    docker run --name my-container -d -v C:\Users\v-adamarla\Desktop\AutomationApk\PartnerDevices_Automation:C:\app\mounted-folder my-custom-image:latest powershell -Command "Start-Sleep -Seconds 3600"
  displayName: 'Run Docker Container with Mounted Volume'

- script: |
    echo "Running Robot Framework tests..."
    docker exec my-container powershell -Command "cd C:\app\mounted-folder; robot -d results\t -i 308426 tests"
  displayName: 'Run Robot Framework Tests'

- script: |
    echo "Stopping Docker container..."
    docker stop my-container
    docker rm my-container
  displayName: 'Stop and Remove Docker Container'
