# Azure Pipeline to Build Docker and Manage Android SDK Licenses

trigger:
- main

pool:
  vmImage: 'windows-latest'
  name: Default

steps:
- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: 'windows-image:latest'

- script: |
    docker rm -f android-container || echo "No existing container to remove"
    docker run --name android-container windows-image:latest "C:\android-sdk\cmdline-tools\latest\bin\sdkmanager.bat" --licenses
  displayName: 'Run SDK Manager in Docker Container'
  
- script: |
    docker exec android-container cmd /C "echo Accepting licenses..."
  displayName: 'Accept Licenses in Running Container'
