trigger:
- main

pool:
  vmImage: 'windows-latest'
  name: Default


steps:
- script: |
    echo "Building Docker image..."
    docker build -t android-sdk-image .
  displayName: 'Build Docker Image'

- script: |
    echo "Removing existing container if it exists..."
    docker rm -f android-sdk-container || true
  displayName: 'Remove Existing Container'

- script: |
    echo "Running Docker container..."
    docker run --name android-sdk-container -d android-sdk-image cmd /c "ping -t localhost > NUL"
  displayName: 'Run Docker Container'

- script: |
    echo "Accepting Android SDK licenses..."
    docker exec android-sdk-container cmd /c "for /L %%i in (1,1,7) do (echo y | C:\android-sdk\cmdline-tools\latest\bin\sdkmanager.bat --licenses > NUL)"
  displayName: 'Accept Android SDK Licenses'

- script: |
    echo "Installing Android SDK components..."
    docker exec android-sdk-container C:\android-sdk\cmdline-tools\latest\bin\sdkmanager.bat "platform-tools" "platforms;android-28" "build-tools;28.0.3"
  displayName: 'Install Android SDK Components'

- script: |
    echo "Verifying ADB installation..."
    docker exec android-sdk-container C:\android-sdk\platform-tools\adb.exe version
  displayName: 'Verify ADB Installation'

- script: |
    echo "Running appium-doctor..."
    docker exec android-sdk-container appium-doctor
  displayName: 'Run Appium Doctor'

- script: |
    echo "Cleaning up..."
    docker stop android-sdk-container
    docker rm android-sdk-container
  displayName: 'Clean Up'
