trigger:
- main

pool:
  vmImage: 'windows-latest'
  name: Default

steps:
- checkout: self

- script: |
    echo "Building Docker image..."
    docker build -t android-sdk-image .
  displayName: 'Build Docker Image'

- script: |
    echo "Removing existing container if it exists..."
    docker rm -f android-sdk-container || true
  displayName: 'Remove Existing Container'

- script: |
    echo "Running Docker container..."
    docker run --name android-sdk-container -d android-sdk-image powershell -Command "Start-Sleep -Seconds 3600"
  displayName: 'Run Docker Container'

- script: |
    echo "Accepting Android SDK licenses..."
    docker exec android-sdk-container powershell -Command "
    \$SDKMANAGER = 'C:\\Users\\v-adamarla\\AppData\\Local\\Android\\Sdk\\cmdline-tools\\latest\\bin\\sdkmanager.bat';
    if (Test-Path \$SDKMANAGER) {
        Write-Host 'Found sdkmanager at:' \$SDKMANAGER;
        Write-Host 'Creating temporary response file...';
        'y' | Out-File -FilePath \$env:TEMP\\sdk_response.txt -Encoding ASCII;
        for (\$i=1; \$i -le 6; \$i++) {
            Add-Content -Path \$env:TEMP\\sdk_response.txt -Value 'y';
        }
        Write-Host 'Accepting licenses...';
        & \$SDKMANAGER --licenses < \$env:TEMP\\sdk_response.txt;
        if (\$LASTEXITCODE -eq 0) {
            Write-Host 'Licenses accepted successfully.';
        } else {
            Write-Error 'Failed to accept licenses. Error code:' \$LASTEXITCODE;
            exit 1;
        }
        Remove-Item \$env:TEMP\\sdk_response.txt;
    } else {
        Write-Error 'sdkmanager not found at expected location. Please check your Android SDK installation.';
        exit 1;
    }
    "
  displayName: 'Accept Android SDK Licenses'

- script: |
    echo "Cleaning up..."
    docker stop android-sdk-container
    docker rm android-sdk-container
  displayName: 'Clean Up'
